### ISSUE TITLE
Installation on M2.2.2

### ISSUE THREAD

**Issue by andy-rush-beerhawk** [aune-io/magento2-product-category-url-fix#1]
Hi, we are looking to integrate this module on a Magento 2.2.2 system.
However we cannot use composer as the modules composer.json only allows Magento versions 2.1.*.
Can you update the composer.json file please.
Regards

**Comment by renatocason** [comment]
Hi @andy-rush-beerhawk ,

That should be fixed now, let me know if you have any issue!

Regards,
Renato
