### ISSUE TITLE
Installation on M2.2.4-CE

### ISSUE THREAD

**Issue by leon-fb** [aune-io/magento2-product-category-url-fix#2]
composer require aune-io/magento2-product-category-url-fix
Using version ^1.1 for aune-io/magento2-product-category-url-fix
./composer.json has been updated
Loading composer repositories with package information                                                                  Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aune-io/magento2-product-category-url-fix 1.1.0 requires php-coveralls/php-coveralls ~2.0.0 -> satisfiable by php-coveralls/php-coveralls[v2.0.0].
    - Conclusion: remove symfony/console v2.8.41
    - Conclusion: don't install symfony/console v2.8.41
...etc

**Comment by renatocason** [comment]
Hi @leon-fb ,

Thanks for reporting the issue. Can you try again with version 1.1.1 and let me know if it works for you as well?

Thanks,
Renato

**Comment by leon-fb** [comment]
Hi @renatocason ,

Works perfectly now, thanks!

Best regards,
Leon

**Comment by fballiano** [comment]
Hi @renatocason, I think this issue came back again, same as https://github.com/aune-io/magento2-autoinvoice/issues/11 :-)

**Comment by renatocason** [comment]
Version 1.2.2 should fix this @fballiano , let me know!

**Comment by fballiano** [comment]
still not working :-(

```
composer require aune-io/magento2-product-category-url-fix:1.2.2 --ignore-platform-reqs
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aune-io/magento2-product-category-url-fix 1.2.2 -> satisfiable by aune-io/magento2-product-category-url-fix[1.2.2].
    - Conclusion: remove psr/log 1.1.3
    - Conclusion: don't install psr/log 1.1.3
    - aune-io/magento2-product-category-url-fix 1.2.2 requires psr/log 1.0.2|1.1.0 -> satisfiable by psr/log[1.0.2, 1.1.0].
    - Can only install one of: psr/log[1.0.2, 1.1.3].
    - Can only install one of: psr/log[1.1.0, 1.1.3].
    - Installation request for psr/log (locked at 1.1.3) -> satisfiable by psr/log[1.1.3].
```

Thanks!

**Comment by renatocason** [comment]
Ok, it looks like psr/log was updated in some of the later versions of 2.2. Can you give a try to what's on the master branch now? If that works I will create a new release with that.

Thanks,
Renato

**Comment by fballiano** [comment]
not sure if I'm doing something wrong but:

```
composer require aune-io/magento2-product-category-url-fix:dev-master --ignore-platform-reqs
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aune-io/magento2-product-category-url-fix dev-master -> satisfiable by aune-io/magento2-product-category-url-fix[dev-master].
    - Conclusion: remove psr/log 1.1.3
    - Conclusion: don't install psr/log 1.1.3
    - aune-io/magento2-product-category-url-fix dev-master requires psr/log ~1.0.2|1.1.0 -> satisfiable by psr/log[1.0.2, 1.1.0].
    - Can only install one of: psr/log[1.0.2, 1.1.3].
    - Can only install one of: psr/log[1.1.0, 1.1.3].
    - Installation request for psr/log (locked at 1.1.3) -> satisfiable by psr/log[1.1.3].
```

Am I wrong or there's no logging in the module? maybe the psr/log could be removed?

**Comment by renatocason** [comment]
You are right, I probably copied and pasted that dependency from another project... Or removed some kind of logging at some point.
Anyway, I removed that now. Should finally work! (version 1.2.3)

**Comment by fballiano** [comment]
it worked :-) thanks a lot!
